### ISSUE TITLE
Incompatibility with node.js > 12 due to SetHeader 

### ISSUE THREAD

**Issue by Ilko** [primus/access-control#42]
Please upgrade setHeader to 1.0.2 (https://github.com/primus/primus/issues/741)

**Comment by lpinca** [comment]
A [tilde range](https://docs.npmjs.com/cli/v7/using-npm/semver#tilde-ranges-123-12-1) is used for the [dependency](https://github.com/primus/access-control/blob/1.0.1/package.json#L39). This means that `setheader@1.0.2` will be used the next time `access-control` is installed. If you are using a lock file, update it.

I'm closing this as answered. Discussion can continue if needed.
